### ISSUE TITLE
Partitioner lambda function failing due to YAML import

### ISSUE THREAD

**Issue by kwkeefer** [duo-labs/cloudtrail-partitioner#3]
My Partitioner function is failing with the error below:
[ERROR] Runtime.ImportModuleError: Unable to import module 'main': No module named 'yaml'

I commented out the import yaml line, as well as the lines that try to read the yaml config file, and it seems to have resolved the issue.

**Comment by 0xdabbad00** [comment]
I'm guessing you didn't run the initial setup. Pleas run:
```
cd resources/partitioner
pip3 install pyyaml boto3 -t .
python3 main.py
```

**Comment by kwkeefer** [comment]
Ah, no, you're right - I didn't see that pip3 was installing the packages locally so I skipped that step since I already had those installed.  My bad - thanks for the reply.
