### ISSUE TITLE
Using AWS Organisation

### ISSUE THREAD

**Issue by dangul** [duo-labs/cloudtrail-partitioner#8]
Hi, when using AWS organisations the logfile path need to be changed. I added organisation id after AWSLogs and did a redeploy but I think the best is to let the config handle it.

```
209c209
<     log_path_prefix = log_path_prefix + "AWSLogs/"
---
>     log_path_prefix = log_path_prefix + "AWSLogs/[AWSORGANISATIONID]/"
```

**Comment by 0xdabbad00** [comment]
That code change is unnecessary. cloudtrail-partitioner's main use case is working on S3 buckets that have Organization trail's writing to them so this is already accounted for in the code. See https://github.com/duo-labs/cloudtrail-partitioner/blob/master/resources/partitioner/main.py#L223

**Comment by dangul** [comment]
Ah alright, great ! I didn´t know that... Maybe worth mention in README ?
